<?php

namespace ShoeShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ButyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ButyRepository extends EntityRepository
{
}
