<?php

namespace ShoeShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RozmiarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RozmiarRepository extends EntityRepository
{

}
